/*
 * Generated File : Remote_SceneControllerBase
 * 
 * This code has been generated by the CodeGenerator.
 * Do not modify the code arbitrarily.
 */

#nullable enable
#pragma warning disable CS0649

using System;
using System.Numerics;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using CT.Common;
using CT.Common.DataType;
using CT.Common.Exceptions;
using CT.Common.Gameplay;
using CT.Common.Quantization;
using CT.Common.Serialization;
using CT.Common.Synchronizations;
using CT.Common.Tools;
using CT.Common.DataType.Input;
using CT.Common.DataType.Primitives;
using CT.Common.DataType.Synchronizations;
using CT.Common.Gameplay.Dueoksini;
using CT.Common.Gameplay.Infos;
using CT.Common.Gameplay.PlayerCharacterStates;
using CT.Common.Gameplay.Players;
using CT.Common.Gameplay.RedHood;
using CT.Common.Tools.CodeGen;
using CT.Common.Tools.Collections;
using CT.Common.Tools.ConsoleHelper;
using CT.Common.Tools.Data;
using CT.Common.Tools.FSM;
using CT.Common.Tools.GetOpt;
using CT.Common.Tools.SharpJson;
using CTC.Networks.Synchronizations;

namespace CTC.Networks.SyncObjects.SyncObjects
{
	[Serializable]
	public partial class SceneControllerBase
	{
		public override NetworkObjectType Type => NetworkObjectType.SceneControllerBase;
		[SyncRpc(dir: SyncDirection.FromRemote)]
		public partial void Client_OnSceneLoaded();
		[SyncVar]
		protected GameSceneIdentity _gameSceneIdentity = new();
		public GameSceneIdentity GameSceneIdentity => _gameSceneIdentity;
		protected Action<GameSceneIdentity>? _onGameSceneIdentityChanged;
		public event Action<GameSceneIdentity> OnGameSceneIdentityChanged
		{
			add => _onGameSceneIdentityChanged += value;
			remove => _onGameSceneIdentityChanged -= value;
		}
		[SyncRpc]
		public virtual partial void Server_TryLoadSceneAll(GameSceneIdentity gameScene);
		[SyncRpc(SyncType.ReliableTarget)]
		public virtual partial void Server_TryLoadScene(GameSceneIdentity gameScene);
		public SceneControllerBase()
		{
		}
		protected BitmaskByte _dirtyReliable_0 = new();
		public partial void Client_OnSceneLoaded()
		{
			Client_OnSceneLoadedCallstackCount++;
			_dirtyReliable_0[0] = true;
			MarkDirtyReliable();
		}
		protected byte Client_OnSceneLoadedCallstackCount = 0;
		public override void ClearDirtyReliable()
		{
			_isDirtyReliable = false;
			_dirtyReliable_0.Clear();
			Client_OnSceneLoadedCallstackCount = 0;
		}
		public override void ClearDirtyUnreliable() { }
		public override void SerializeSyncReliable(IPacketWriter writer)
		{
			_dirtyReliable_0.Serialize(writer);
			if (_dirtyReliable_0[0])
			{
				writer.Put((byte)Client_OnSceneLoadedCallstackCount);
			}
		}
		public override void SerializeSyncUnreliable(IPacketWriter writer) { }
		public override void InitializeMasterProperties() { }
		public override bool TryDeserializeSyncReliable(IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				if (!_gameSceneIdentity.TryDeserialize(reader)) return false;
				_onGameSceneIdentityChanged?.Invoke(_gameSceneIdentity);
			}
			if (dirtyReliable_0[1])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity gameScene = new();
					if (!gameScene.TryDeserialize(reader)) return false;
					Server_TryLoadSceneAll(gameScene);
				}
			}
			if (dirtyReliable_0[2])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity gameScene = new();
					if (!gameScene.TryDeserialize(reader)) return false;
					Server_TryLoadScene(gameScene);
				}
			}
			return true;
		}
		public override bool TryDeserializeSyncUnreliable(IPacketReader reader) => true;
		public override bool TryDeserializeEveryProperty(IPacketReader reader)
		{
			if (!_gameSceneIdentity.TryDeserialize(reader)) return false;
			return true;
		}
		public override void InitializeRemoteProperties()
		{
			_gameSceneIdentity = new();
		}
		public override void IgnoreSyncReliable(IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				GameSceneIdentity.IgnoreStatic(reader);
			}
			if (dirtyReliable_0[1])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity.IgnoreStatic(reader);
				}
			}
			if (dirtyReliable_0[2])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity.IgnoreStatic(reader);
				}
			}
		}
		public static void IgnoreSyncStaticReliable(IPacketReader reader)
		{
			BitmaskByte dirtyReliable_0 = reader.ReadBitmaskByte();
			if (dirtyReliable_0[0])
			{
				GameSceneIdentity.IgnoreStatic(reader);
			}
			if (dirtyReliable_0[1])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity.IgnoreStatic(reader);
				}
			}
			if (dirtyReliable_0[2])
			{
				byte count = reader.ReadByte();
				for (int i = 0; i < count; i++)
				{
					GameSceneIdentity.IgnoreStatic(reader);
				}
			}
		}
		public override void IgnoreSyncUnreliable(IPacketReader reader) { }
		public static void IgnoreSyncStaticUnreliable(IPacketReader reader) { }
	}
}
#pragma warning restore CS0649
